# Generated by Django 5.2.5 on 2025-08-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('attribution_confidence', models.IntegerField(blank=True, null=True)),
                ('suspected_state_sponsor', models.CharField(blank=True, max_length=100, null=True)),
                ('target_category', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActorReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_url', models.URLField(max_length=500)),
                ('threat_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='mispgalaxy.threatactor')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActorSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('threat_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='mispgalaxy.threatactor')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActorVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim', models.CharField(max_length=255)),
                ('threat_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='mispgalaxy.threatactor')),
            ],
        ),
    ]
